import {
    DefaultButton,
    Dialog,
    DialogFooter,
    DialogType,
    IContextualMenuProps,
    IconButton,
    ImageFit,
    Label,
    Link,
    MessageBar,
    MessageBarType,
    Persona,
    PersonaSize,
    PrimaryButton,
    SearchBox,
    Separator,
    ShimmeredDetailsList,
    Spinner,
    SpinnerSize,
    Stack,
    getTheme
  } from '@fluentui/react';